Repository Airdnd-05/airdnd, pull requests merged in 2024-05, with the labels that each got.

#12 [Feat] Next 라우팅 설정
  .env
  next.config.mjs
  public/data/Accommodation.json
  src/app/api/accommodations/route.js
  src/app/page.tsx
  src/app/rooms/[id]/page.tsx
Labels: feature, frontend

#14 [Feat] shadcn/ui의 carousel 컴포넌트를 설치
  components.json
  package-lock.json
  package.json
  src/app/globals.css
  src/app/rooms/[id]/page.tsx
  src/components/accommodation/briefInfo/BedsInfo.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: chore, frontend

#17 [Refactor] formatingPrice 파일 안에 함수 구현 후 ReservationCard에 적용
  src/components/accommodation/briefInfo/BriefInfo.tsx
  src/components/accommodation/briefInfo/ReservationCard.tsx
  src/components/accommodation/detailBanner/DetailPageBanner.tsx
  src/utils/formatingPrice.ts
Labels: frontend, refactor, style

#19 Detail Page에 컴포넌트 추가
  src/components/accommodation/briefInfo/AccomodationDesc.tsx
  src/components/accommodation/briefInfo/BriefInfo.tsx
  src/components/accommodation/briefInfo/HostProfile.tsx
  src/components/accommodation/briefInfo/ReservationCard.tsx
Labels: feature, frontend
