Repository Airdnd-05/airdnd, pull requests merged in 2024-06, with the labels that each got.

#26 [Feat] API 작성 및 데이터fetch 방식 변경
  package-lock.json
  package.json
  public/data/Accommodation.json
  public/data/Host.json
  public/images/SquareBracketRight.svg
  src/app/api/accommodations/route.js
  src/app/api/fetchHostData/route.js
  src/app/api/fetchRoomsData/route.js
  src/app/api/guestFavorite/route.js
  src/app/page.tsx
  src/app/rooms/[id]/page.tsx
  src/components/accommodation/amenityInfo/AmenityInfo.tsx
  src/components/accommodation/briefInfo/AccommodationDesc.tsx
  src/components/accommodation/briefInfo/AccomodationDesc.tsx
  src/components/accommodation/briefInfo/BriefInfo.tsx
  src/components/accommodation/briefInfo/GuestFavorite.tsx
  src/components/accommodation/briefInfo/HostProfile.tsx
  src/components/accommodation/briefInfo/NonGuestFavorite.tsx
  src/components/accommodation/briefInfo/RoomBedsInfo.tsx
  src/components/accommodation/briefInfo/Summary.tsx
  src/components/accommodation/detailBanner/DetailPageBanner.tsx
  src/components/accommodation/detailBanner/HeartButton.tsx
  src/components/accommodation/hostDetail/BeginnerHostInfoBox.tsx
  src/components/accommodation/hostDetail/HostDetail.tsx
  src/components/accommodation/hostDetail/HostDetailInfo.tsx
  src/components/accommodation/hostDetail/HostInfoBox.tsx
  src/components/accommodation/hostDetail/HostIntro.tsx
  src/components/common/layout/Header.tsx
  src/components/common/layout/Header[x].tsx
  src/utils/fetchAccommodations.js
  src/utils/fetchHostData.js
  src/utils/fetchRoomsData.js
Labels: backend, feature, frontend

#28 [Chore] ESLint 설정 적용
  .eslintrc.js
  .eslintrc.json
  .prettierrc
  .prettierrc.json
  package-lock.json
  package.json
  public/data/host-detail.json
  src/app/api/accommodations/route.js
  src/app/api/fetchHostData/route.js
  src/app/api/fetchRoomsData/route.js
  src/app/layout.tsx
  src/app/page.tsx
  src/app/rooms/[id]/layout.tsx
  src/app/rooms/[id]/page.tsx
  src/components/accommodation/amenityInfo/AmenityInfo.tsx
  src/components/accommodation/briefInfo/AccommodationDesc.tsx
  src/components/accommodation/briefInfo/BedsInfo.tsx
  src/components/accommodation/briefInfo/BriefInfo.tsx
  src/components/accommodation/briefInfo/GuestFavorite.tsx
  src/components/accommodation/briefInfo/HostProfile.tsx
  src/components/accommodation/briefInfo/NonGuestFavorite.tsx
  src/components/accommodation/briefInfo/ReservationCard.tsx
  src/components/accommodation/briefInfo/RoomBedsInfo.tsx
  src/components/accommodation/briefInfo/Summary.tsx
  src/components/accommodation/detailBanner/DetailPageBanner.tsx
  src/components/accommodation/detailBanner/HeartButton.tsx
  src/components/accommodation/hostDetail/BeginnerHostInfoBox.tsx
  src/components/accommodation/hostDetail/HostDetail.tsx
  src/components/accommodation/hostDetail/HostDetailInfo.tsx
  src/components/accommodation/hostDetail/HostInfoBox.tsx
  src/components/accommodation/hostDetail/HostIntro.tsx
  src/components/accommodationCard/card.tsx
  src/components/accommodationCard/cardCss.css
  src/components/accommodationCard/swiper.tsx
  src/components/common/Footer/FooterInfoItem.tsx
  src/components/common/Footer/FooterSection.tsx
  src/components/common/Header/HeaderNavItem.tsx
  src/components/common/Header/HeaderProfile.tsx
  src/components/common/Header/HeaderProfileItem.tsx
  src/components/common/Header/SearchBar.tsx
  src/components/common/button/FilterButton.tsx
  src/components/common/layout/Footer.tsx
  src/components/common/layout/Header.tsx
  src/components/common/layout/Header[x].tsx
  src/components/common/layout/Layout.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/context/AccommodationContext.js
  src/hooks/useOnclickOutside.jsx
  src/lib/utils.ts
  src/modals/HeaderProfileModal.tsx
  src/modals/LoginModal.tsx
  src/utils/fetchAccommodations.js
  src/utils/fetchHostData.js
  src/utils/fetchRoomsData.js
  tailwind.config.ts
  tsconfig.json
Labels: chore, frontend

#31 [Fix] Next/Image에서 요구하는 props를 설정하여 실행시 보이는 warn을 제거
  .eslintrc.js
  src/app/api/accommodations/route.js
  src/app/page.tsx
  src/app/rooms/[id]/page.tsx
  src/components/accommodation/amenityInfo/AmenityInfo.tsx
  src/components/accommodation/briefInfo/BedsInfo.tsx
  src/components/accommodation/briefInfo/NonGuestFavorite.tsx
  src/components/accommodation/detailBanner/DetailPageBanner.tsx
  src/components/accommodation/hostDetail/HostInfoBox.tsx
  src/components/accommodation/hostDetail/HostIntro.tsx
  src/components/accommodation/infoWrapper/AccommodationDesc.tsx
  src/components/accommodation/infoWrapper/BedsInfo.tsx
  src/components/accommodation/infoWrapper/GuestFavorite.tsx
  src/components/accommodation/infoWrapper/HostProfile.tsx
  src/components/accommodation/infoWrapper/InfoWrapper.tsx
  src/components/accommodation/infoWrapper/ReservationCard.tsx
  src/components/accommodation/infoWrapper/RoomsBriefInfo.tsx
  src/components/card/button.tsx
  src/components/card/card.tsx
  src/components/card/carousel.tsx
  src/components/common/Footer/FooterSection.tsx
  src/components/common/Header/HeaderProfile.tsx
  src/components/common/Header/SearchBar.tsx
  src/components/common/button/FilterButton.tsx
  src/components/common/layout/Footer.tsx
  src/components/common/layout/Header.tsx
  src/components/common/layout/Header[x].tsx
  src/context/AccommodationContext.js
Labels: bug, frontend

#33 [Fix] API의 JSON import시 비동기 작업에 발생되는 문제를 fetch로 대체하여 해결
  src/app/api/accommodations/route.js
  src/app/api/fetchHostData/route.js
  src/app/api/fetchRoomsData/route.js
Labels: bug, frontend

#38 [Feat] 전역 상태 관리를 위한 Redux Toolkit 사용환경 설정
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/accommodation/category/CarouselCategory.tsx
  src/components/accommodation/category/ui/card.tsx
  src/components/accommodation/category/ui/carousel.tsx
  src/components/accommodation/hostDetail/HostDetail.tsx
  src/components/common/button/FilterButton.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
  src/modals/FilterModal.tsx
  src/modals/ReviewModal.tsx
  src/modals/signUpModal.tsx
  src/redux/Providers.tsx
  src/redux/features/filter/slice.ts
  src/redux/features/modal/slice.ts
  src/redux/features/review/slice.ts
  src/redux/features/signup/slice.ts
  src/redux/store.ts
Labels: feature, frontend

#40 더미 JSON 파일을 가져오는 방식 변경
  .github/ISSUE_TEMPLATE/01_feature_addition.yml
  .github/ISSUE_TEMPLATE/02_feature_removal.yml
  .github/ISSUE_TEMPLATE/03_bug_report.yml
  .github/pull_request_template.md
  src/app/api/accommodations/route.js
  src/app/api/fetchHostData/route.js
  src/app/api/fetchRoomsData/route.js
  src/app/apis/fetchHostData/getHostDetail.ts
  src/app/apis/fetchHostData/route.ts
  src/app/apis/fetchMainPage/getRoomsList.ts
  src/app/apis/fetchMainPage/route.ts
  src/app/apis/fetchRoomsData/getRoomsDetail.ts
  src/app/apis/fetchRoomsData/route.ts
  src/app/page.tsx
  src/components/accommodation/amenityInfo/AmenityInfo.tsx
  src/components/accommodation/detailBanner/DetailPageBanner.tsx
  src/components/accommodation/hostDetail/HostDetail.tsx
  src/components/accommodation/infoWrapper/AccommodationDesc.tsx
  src/components/accommodation/infoWrapper/GuestFavorite.tsx
  src/components/accommodation/infoWrapper/HostProfile.tsx
  src/components/accommodation/infoWrapper/InfoWrapper.tsx
  src/components/accommodation/infoWrapper/RoomsBriefInfo.tsx
  src/components/common/button/FilterButton.tsx
  src/modals/FilterModal.tsx
  src/redux/features/filter/slice.ts
  src/redux/features/modal/slice.ts
  src/redux/store.ts
  src/utils/fetchAccommodations.js
  src/utils/fetchHostData.js
  src/utils/fetchRoomsData.js
Labels: backend, chore, frontend, refactor

#41 [Refactor] 호스트 상세 정보 세부 조정
  public/data/Host.json
  src/app/rooms/[id]/page.tsx
  src/components/accommodation/hostDetail/BeginnerHostInfoBox.tsx
  src/components/accommodation/hostDetail/ExperiencedHostInfoBox.tsx
  src/components/accommodation/hostDetail/HostDetail.tsx
  src/components/accommodation/hostDetail/HostDetailContainer.tsx
  src/components/accommodation/hostDetail/HostDetailInfo.tsx
  src/components/accommodation/hostDetail/HostIntro.tsx
  tailwind.config.ts
Labels: design, frontend, refactor

#45 [Feat] 캘린더 추가
  package-lock.json
  package.json
  src/app/rooms/[id]/page.tsx
  src/components/calendar/calendar.css
  src/components/calendar/calendar.tsx
  src/utils/formatingDate.ts
Labels: feature, frontend

#47 [Fix] 카테고리 케로셀 종단 슬라이드를 벗어날 때 멈추는 오류 해결
  src/components/accommodation/categoryBundle/ui/carousel.tsx
Labels: bug, frontend

#50 [Chore] 이슈 템플릿 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/01_feature_addition.yml
  .github/ISSUE_TEMPLATE/02_feature_removal.yml
  .github/ISSUE_TEMPLATE/06-chore.yml
  .github/pull_request_template.md
  public/data/Accommodation.json
Labels: chore

#52 [Feat] 메인 페이지의 렌더링에 필요한 정보를 가져오는 API 로직을 변경
  src/app/apis/fetchMainPage/getRoomsList.ts
  src/app/apis/fetchMainPage/route.ts
  src/app/page.tsx
  src/components/accommodation/categoryBundle/Category.tsx
  src/components/calendar/calendar.tsx
Labels: backend, feature, frontend

#53 [Feat] 메인 페이지의 (숙소 정보가 담긴) 카드 무한 스크롤
  src/app/apis/fetchMainPage/route.ts
  src/app/page.tsx
  src/components/infiniteScroll/scroll.tsx
Labels: feature, frontend

#55 네비게이션바 검색창 및 메인페이지 필터 모달을 위한 Redux 설정
  .eslintrc.js
  package-lock.json
  package.json
  public/data/Rooms.json
  public/images/BuildingTypeApart.jpg
  public/images/BuildingTypeHome.jpg
  public/images/BuildingTypeHotel.jpg
  public/images/BuildingTypeVilla.jpg
  public/images/WingAll.svg
  src/SearchModal/TravelersModal.tsx
  src/app/Providers.tsx
  src/app/apis/fetchFilterData/route.ts
  src/app/layout.tsx
  src/components/accommodation/categoryBundle/Category.tsx
  src/components/accommodation/categoryBundle/ui/carousel.tsx
  src/components/accommodation/infoWrapper/InfoWrapper.tsx
  src/components/common/Header/SearchBar.tsx
  src/components/filters/AmenitiesFilter.tsx
  src/components/filters/BedFilter.tsx
  src/components/filters/BookingOptionFilter.tsx
  src/components/filters/BuildingTypeFilter.tsx
  src/components/filters/GuestFavoriteFilter.tsx
  src/components/filters/PriceRangeFilter.tsx
  src/components/filters/RoomTypeFilter.tsx
  src/modals/FilterModal.tsx
  src/modals/FilterModalButton.tsx
  src/modals/TravelersModalButton.tsx
  src/redux/apiSlice.ts
  src/redux/features/amenitiesFilterSlice.ts
  src/redux/features/bedFilterSlice.ts
  src/redux/features/bookingOptionFilterSlice.ts
  src/redux/features/buildingTypeFilterSlice.ts
  src/redux/features/buildingTypeSlice.ts
  src/redux/features/cityFilterSlice.ts
  src/redux/features/dateFilterSlice.ts
  src/redux/features/filterSlice.ts
  src/redux/features/guestFavoriteFilterSlice.ts
  src/redux/features/guestFavoriteSlice.ts
  src/redux/features/modal/slice.ts
  src/redux/features/modalSlice.ts
  src/redux/features/priceRangeFilterSlice.ts
  src/redux/features/review/slice.ts
  src/redux/features/roomTypeFilterSlice.ts
  src/redux/features/signup/slice.ts
  src/redux/features/travelersFilterSlice.ts
  src/redux/store.ts
  src/types/Filters.ts
Labels: feature, frontend

#57 [Fix] 필터 모달의 기능 오류를 해결
  public/data/Rooms.json
  src/app/apis/fetchFilterData/route.ts
  src/components/accommodation/infoWrapper/InfoWrapper.tsx
  src/modals/ReviewModal.tsx
  src/modals/signUpModal.tsx
  src/redux/features/buildingTypeSlice.ts
  src/redux/features/guestFavoriteSlice.ts
  src/types/Filters.ts
Labels: feature, frontend

#61 [Feature] ReservationCard CalendarModal 기능 구현
  src/app/rooms/[id]/page.tsx
  src/components/accommodation/AccommodationDate.tsx
  src/components/accommodation/amenityInfo/AmenityInfo.tsx
  src/components/accommodation/detailCalendar.tsx
  src/components/accommodation/hostDetail/HostDetailContainer.tsx
  src/components/accommodation/infoWrapper/BedsInfo.tsx
  src/components/accommodation/infoWrapper/HostProfile.tsx
  src/components/accommodation/infoWrapper/InfoWrapper.tsx
  src/components/accommodation/infoWrapper/ReservationCard.tsx
  src/components/accommodation/infoWrapper/RoomsBriefInfo.tsx
  src/components/accommodation/infoWrapper/reservationCard/CalendarModalButton.tsx
  src/components/accommodation/infoWrapper/reservationCard/ReservationCalendarModal.tsx
  src/components/accommodation/infoWrapper/reservationCard/ReservationCard.tsx
  src/components/calendar/calendar.tsx
  src/components/common/calendar/calendar.css
  src/components/common/calendar/calendar.tsx
  src/hooks/useCalendar.tsx
  src/modals/RefreshDateButton.tsx
  src/redux/features/calendar/slice.ts
  src/redux/store.ts
  src/utils/dateToString.ts
  src/utils/formatingDate.ts
Labels: design, feature, frontend

#62 [Fix] RefreshDateButton 위치 수정
  src/components/accommodation/detailCalendar.tsx
  src/components/accommodation/infoWrapper/reservationCard/ReservationCalendarModal.tsx
  src/components/common/calendar/RefreshDateButton.tsx
Labels: bug

#65 [Design] 카드와 카테고리 CSS 수정
  src/components/accommodation/categoryBundle/Category.tsx
  src/components/accommodation/infoWrapper/GuestFavorite.tsx
  src/components/accommodation/infoWrapper/RoomsBriefInfo.tsx
  src/components/card/card.tsx
  src/components/card/carousel.tsx
  src/modals/FilterModalButton.tsx
Labels: design, frontend

#73 [Refactor] 캘린더 CSS 구조 변경
  src/components/common/calendar/calendar.css
  src/components/common/searchNav/SearchModal/SearchModal.tsx
  src/components/common/searchNav/searchbar/CheckOut.tsx
  src/components/detailPage/infoWrapper/reservationCard/CalendarModalButton.tsx
  src/components/detailPage/infoWrapper/reservationCard/GuestModalButton.tsx
Labels: design, frontend, refactor
